### ISSUE TITLE
[Add] Sprites

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanSignalSet#1]
## 구식(완목식) 신호기
![구식 폐색](https://user-images.githubusercontent.com/77984422/113133004-29be9580-925a-11eb-8624-31f5c8272556.png)
![구식 입구](https://user-images.githubusercontent.com/77984422/113133146-4c50ae80-925a-11eb-9ecd-2c728a8a7844.png)
![구식 출구](https://user-images.githubusercontent.com/77984422/113133152-4e1a7200-925a-11eb-95b1-b94342b1d50b.png)
![구식 복합](https://user-images.githubusercontent.com/77984422/113133157-4f4b9f00-925a-11eb-927e-602030fde3c8.png)
![구식 프로그램](https://user-images.githubusercontent.com/77984422/113133262-68ece680-925a-11eb-943b-56c729d14125.png)
![구식 경로](https://user-images.githubusercontent.com/77984422/113133268-6be7d700-925a-11eb-97b3-042d10517e4d.png)
![구식 경로(단방향)](https://user-images.githubusercontent.com/77984422/113133272-6d190400-925a-11eb-9fe6-86af12536d4f.png)

## 전자식(색등식) 신호기
![전자식 폐색](https://user-images.githubusercontent.com/77984422/113133314-7a35f300-925a-11eb-912f-3f057e03a990.png)
![전자식 입구](https://user-images.githubusercontent.com/77984422/113133321-7bffb680-925a-11eb-997d-3688d404a7bd.png)
![전자식 출구](https://user-images.githubusercontent.com/77984422/113133326-7d30e380-925a-11eb-87a0-34a3ed76ccbc.png)
![전자식 복합](https://user-images.githubusercontent.com/77984422/113133331-7efaa700-925a-11eb-937f-c57eb1f49f97.png)
![전자식 프로그램](https://user-images.githubusercontent.com/77984422/113133341-802bd400-925a-11eb-9126-17cf7750106c.png)
![전자식 경로](https://user-images.githubusercontent.com/77984422/113133362-85891e80-925a-11eb-9976-eb1d6e8f0df1.png)
![전자식 경로(단방향)](https://user-images.githubusercontent.com/77984422/113133366-86ba4b80-925a-11eb-9e56-3b64a31f337c.png)

## 인터페이스
![인터페이스](https://user-images.githubusercontent.com/77984422/113133394-8d48c300-925a-11eb-9086-4e4a74511920.png)
  
  
  
## features
해당 신호기들의 역할에 주목, 각 신호기에 맞는 신호부속기/표지를 추가하여 플레이를 좀 더 다채롭게 만들고 타 신호기 세트와 차별점을 두기 위해 다음과 같이 제작하였습니다.

1. 한국철도의 신호기와 최대한 같게 만듦
2. 고속철도에 어울리는 TVM 신호 시스템의 폐색 표지 추가(구식 폐색 신호기 대체)
3. 복복선 구간의 신호 구분을 위한 파란색 진행신호 추가
4. 추후를 대비한 경계(YY), 주의(Y), 감속(YG) 더미 스프라이트 추가 및 출구, 복합 신호기의 진행 신호를 Y, YG로 변경
5. (매개변수 설정을 통해 게임성 특화 / 고증 특화를 선택) - 예정
6. 인터페이스의 아이콘 변경
7. JGRPP의 프로그램 신호기 스프라이트 변경

**Comment by telk5093** [comment]
일단 이 이슈는 버그가 아닌 정보성 문서이므로, Wiki를 활성화해놓을테니 거기에 별도 문서로 작성해주세요.

**Comment by EightonEight** [comment]
> 일단 이 이슈는 버그가 아닌 정보성 문서이므로, Wiki를 활성화해놓을테니 거기에 별도 문서로 작성해주세요.

위키에 별도 문서로 작성 완료했습니다.
<https://github.com/KoreanGRF/KoreanSignalSet/wiki/Signal-specifications>
