### ISSUE TITLE
[Add] Waypoint sprites

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanSignalSet#10]
![경유지](https://user-images.githubusercontent.com/77984422/113959647-36487c80-985e-11eb-8f7e-426a4319b361.png)
### 1. 입환 신호기
- 전자식 프로그램 신호기에 있던 것을 경유지로도 추가 (#8)
- 정적(R, B 따로)으로 할지 동적(1초마다 R, B 변경)으로 할지 논의 필요 (아래 예상도 참고)
![입환신호기 예상도](https://user-images.githubusercontent.com/77984422/113959841-81628f80-985e-11eb-90f5-a630ca062cb9.gif)

### 2. 3. 4. 임시 신호기
- 서행예고신호기, 서행신호기, 서행해제신호기
- 경유지에서 시간표를 이용하여 속력 제한을 걸 수 있다는 것에 착안
- reference: <https://blog.daum.net/kyung7/12880142>
![image](https://user-images.githubusercontent.com/77984422/113960580-a7d4fa80-985f-11eb-8c71-20d76708f135.png)

**Comment by telk5093** [comment]
1. 제 생각에는 정적인 편이 나을 것 같습니다.

**Comment by telk5093** [comment]
또한 경유지는 내부적으로 역(station)으로 처리되기 때문에 NML로 구현이 불가능합니다.
신호기 세트에서 구현할 수 없을 것 같습니다.
@kiwitreekor Kiwitree Korean Station Set에서 가져가시는 게 어떨까요?

**Comment by EightonEight** [comment]
> 1. 제 생각에는 정적인 편이 나을 것 같습니다.

그럼 진행, 정지 현시된 상태 따로 만들면 될 것 같네요.

**Comment by kiwitreekor** [comment]
가능하긴 합니다만, 좀 시간이 걸릴 수는 있습니다.

**Comment by telk5093** [comment]
그럼 그쪽으로 이관하는 걸로 하고 본 이슈는 닫겠습니다.
