### ISSUE TITLE
전자식 경로, 경로(단방향) 신호기 진행 신호 청색으로 변경 안됨

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanSignalSet#12]
매개변수는 만들어져 있으나 해당 스프라이트가 제작되지 않음

실제로 5현시(4등식) 신호기 진행 신호에 청색을 사용하기도 하므로 스프라이트 제작이 필요함
reference: 
- <https://librewiki.net/wiki/%ED%8C%8C%EC%9D%BC:%EC%A7%84%EB%A3%8C%ED%91%9C%EC%8B%9C%EA%B8%B0-%EC%8B%9D%EB%B3%84%ED%91%9C%EC%A7%80.jpg>
![image](https://user-images.githubusercontent.com/77984422/113964264-1f0d8d00-9866-11eb-8914-b08e5c6863ed.png)

- <https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=104300>
![image](https://user-images.githubusercontent.com/77984422/113964391-6005a180-9866-11eb-93aa-dbc555dfd8e1.png)

**Comment by EightonEight** [comment]
![전자식 경로 청색](https://user-images.githubusercontent.com/77984422/113965537-83c9e700-9868-11eb-9c74-447040294422.png)
청색 진행 신호 스프라이트 제작 완료

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/113979585-63a62200-9880-11eb-914c-c71ed39e4afe.png)

@EightonEight 
단방향 경로 신호기(현실)의 S, N방향 가로 픽셀이 기존 것보다 1px씩 긴데 일부로 의도하신 건가요, 아니면 실수인가요?
실수라면 제가 조정하고 의도라면... 제가 할 일이 생기는 상황이네요.

**Comment by EightonEight** [comment]
> 단방향 경로 신호기(현실)의 S, N방향 가로 픽셀이 기존 것보다 1px씩 긴데 일부로 의도하신 건가요, 아니면 실수인가요?
> 실수라면 제가 조정하고 의도라면... 제가 할 일이 생기는 상황이네요.

각도를 생각해서 의도적으로 2px로 만든게 맞습니다. 이전에 보내드렸던 것과 깃헙에 올린것(#1) 에서도 확인이 가능하구요.

다만 실제 신호기의 자동식별표지를 비교해 보면 크기를 1px로 줄여도 될것 같긴 합니다.
ref: <https://blog.naver.com/scw1011/20111640102>
![image](https://user-images.githubusercontent.com/77984422/113983597-0cef1700-9885-11eb-8f29-cd99f67915a4.png)

**Comment by telk5093** [comment]
그럼 1px로 줄인 상태로 적용해도 괜찮을까요

**Comment by EightonEight** [comment]
> 그럼 1px로 줄인 상태로 적용해도 괜찮을까요

그렇게 해주시면 감사하겠습니다.
