### ISSUE TITLE
Useless Track Set와 함께 사용시 N방향(↑) 신호기가 덮어씌워짐

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanSignalSet#15]
![image](https://user-images.githubusercontent.com/10726524/114143363-07f69a00-994f-11eb-967d-0094843c3ec1.png)

조사 필요

**Comment by kiwitreekor** [comment]
한 타일에 두 종류 선로가 있는 게 원인인 것 같은데 확인해보시겠어요?

이게 맞으면 아마 JGRPP 쪽 버그일겁니다.

**Comment by telk5093** [comment]
@kiwitreekor 확인 감사합니다. 해당 문제가 맞는 것 같네요.
![image](https://user-images.githubusercontent.com/10726524/114197866-bd484280-998d-11eb-9b8f-99c6a3a51a0a.png)

**Comment by telk5093** [comment]
JGRPP 0.43.0에서 해결된 것으로 보임
