### ISSUE TITLE
폐색/사전 신호기에 경로 탐색 제한을 걸면 신호기가 돌아감

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanSignalSet#16]
![image](https://user-images.githubusercontent.com/10726524/114649287-3263a100-9d1b-11eb-99ce-d7db8cca8797.png)

경로 제한 신호기를 기본 그래픽으로 보이기 설정을 켜두면 해당 현상 발생

**Comment by EightonEight** [comment]
![image](https://user-images.githubusercontent.com/77984422/114697321-be47ee00-9d58-11eb-958f-a2d91d900d6e.png)
????? 🤔
