### ISSUE TITLE
매개변수 추가 제안 및 확인해야 할 사항

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanSignalSet#2]
## 매개변수
신호기마다 스프라이트를 게임성에 맞출지 고증에 맞출지 선택할 수 있게 함
  
 * **전자식 ○○ 신호기 스프라이트 표시: _▼게임성 특화 / 고증 특화_**
	표시할 신호기 스프라이트 종류를 선택하십시오. 게임성 특화는 기본 신호기의 표지를 활용하고, 고증 특화는 실제 신호기와 비슷하도록 여러 신호기와 표지가 포함됩니다. (기본값: 고증 특화)

 * **구식 폐색 신호기를 TVM 폐색표지로 변경: _예 / 아니요_**
	구식 폐색 신호기를 고속철도에 어울리는 TVM 폐색표지로 변경합니다. 진행/정지 신호가 구별이 되지 않습니다. (기본값: 예)

 * **전자식 폐색 신호기의 진행 신호를 파란색으로 변경: _예 / 아니요_**
	복복선 등 선로가 많은 구간에서 선로 별 신호 현시 구분을 위해 전자식 폐색 신호기의 진행 신호를 초록색에서 파란색으로 변경합니다. (기본값: 아니요)

 * **전자식 출구, 복합 신호기의 진행 신호를 주의, 감속신호로 변경: _예 / 아니요_**
	전자식 출구, 복합 신호기의 진행 신호를 주의(Y), 감속(YG)신호로 변경하여 3현시 또는 4현시 신호를 표현할 수 있게 합니다. (기본값: 예)
  
  
  
## 확인해야 할 사항
- [x] **스프라이트가 팔레트를 맞게 쓰는 지 확인 필요** 

- [x] 현재 신호기 스프라이트 크기는 인터페이스의 신호기 선택 버튼보다 클 수 있음 - 오프셋 조정을 해봐도 안될 경우 아래 2픽셀 삭제할 것

- [x] 스프라이트 오프셋 설정(특히 구식 신호기는 완목이 선로 안쪽을 향해 있음) - 예상도를 기준으로 오프셋을 맞추나, 스프라이트가 겹치는 등 문제가 발생할 경우 오프셋을 어떻게 해야 할지 논의 필요

**Comment by telk5093** [comment]
Animated colour가 하나(Pure red, (255, 0, 0)) 있는 것 말고는 팔레트 오류는 없어보입니다.
이 부분은 제가 일괄적으로 Pseudo red (252, 0, 0)로 변경해서 적용하겠습니다.

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/113547072-2f382900-9628-11eb-8788-81ae49cb81ca.png) 
![image](https://user-images.githubusercontent.com/10726524/113547226-71fa0100-9628-11eb-8183-50f9c649613e.png)


전자식 신호기만 넣은 상태에서 신호기 UI를 본 결과 넘어가지 않습니다.
혹 넘어갔었다고 해도 기본 신호기 그래픽(original_ttd, not OpenGFX)도 넘어가는 경우가 있었기 때문에 큰 지장은 없었을 겁니다.
