### ISSUE TITLE
새 게임 시작 시 다현시 신호기가 바로 적용되지 않음

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanSignalSet#23]
![1](https://user-images.githubusercontent.com/77984422/133870310-41d5df5d-b875-4566-b734-e20751518c91.gif)

새 게임을 시작하면 다현시 신호기가 적용되지 않고, NewGRF 설정에서 변경사항 적용(매개 변수 설정과는 관계없음)을 한번 클릭해주어야 적용됨

**Comment by telk5093** [comment]
JGR 본인이 만든 ``Multi Aspect Signals``에서도 같은 현상이 발생하는 것으로 보아 한국 신호기 세트의 문제가 아닙니다.
