### ISSUE TITLE
TVM 표지가 통행 방향에 맞게 적용되지 않음

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanSignalSet#24]
![2](https://user-images.githubusercontent.com/77984422/133870663-f2969e0b-46a3-4534-afdb-adcb3f258e93.png)

스프라이트가 우측통행용으로 고정됨

**Comment by telk5093** [comment]
게임 중간에 변경시 NewGRF 설정 > '변경사항 적용'을 누를 필요가 있습니다.
새 게임에서 적용시 문제 없이 잘 반영되므로 문제가 있는 상황이 아닙니다.
