### ISSUE TITLE
매개변수로 신호기 현시 수 조절 기능

### ISSUE THREAD

**Issue by kiwitreekor** [KoreanGRF/KoreanSignalSet#25]
3현시(R,Y,G), 4현시(R,Y,YG,G), 5현시(R,YY,Y,YG,G) 중 선택할 수 있는 옵션이 있으면 좋을 것 같습니다.

**Comment by telk5093** [comment]
괜찮은 생각이기는 한데 신호기 마다 3현시만 있는 게 있고 4현시가 존재하는 신호기가 있어서 그래픽 스프라이트가 구현되기 전까지는 어렵습니다.
또, 해당 현시 수를 switch 블록으로 조정할 수 있는지도 확인해야 합니다.

**Comment by EightonEight** [comment]
다현시 신호기를 지원하는 것만 제작하였습니다.
개인적으로는 현시 수를 신호기마다 따로 조절하는 것이 괜찮을 것 같네요.

---
### 폐색 신호기 ###
![block 3 nonreal](https://user-images.githubusercontent.com/77984422/133964990-a8f5dd4b-42c7-4bf5-8f5f-d149bd29e6d3.png)
`block.3.nonreal`

![block 3 real](https://user-images.githubusercontent.com/77984422/133964996-892d6ca5-65ba-4cf6-b1a0-2ea9a82aad60.png)
`block.3.real`

![block 5 nonreal](https://user-images.githubusercontent.com/77984422/133965081-61a8b44b-352e-4ab6-8cfd-88b60dde96a9.png)
`block.5.nonreal`

![block 5 real](https://user-images.githubusercontent.com/77984422/133965095-6ea674f9-8a6f-4e0f-a3fc-0daf43999991.png)
`block.5.real`

---
### 단방향 경로 신호기 ###
![oneway_path 3 nonreal](https://user-images.githubusercontent.com/77984422/133965139-4a2ec483-79f6-42cd-80c8-fe5424b34d27.png)
`oneway_path.3.nonreal`

![oneway_path 3 real](https://user-images.githubusercontent.com/77984422/133965149-c4531e0c-b287-4813-90ac-a2f1f614ed71.png)
`oneway_path.3.real`

![oneway_path 4 nonreal](https://user-images.githubusercontent.com/77984422/133965163-0ea60dc9-0655-4244-95ad-5c261260caca.png)
`oneway_path.4.nonreal`

![oneway_path 4 real](https://user-images.githubusercontent.com/77984422/133965179-9203c43a-3577-4dcb-9a8a-5026d26fe07e.png)
`oneway_path.4.real`

---
### 경로 신호기 ###
![path 3 nonreal](https://user-images.githubusercontent.com/77984422/133965208-ae3b2689-86bd-4691-abee-f4662ec00180.png)
`path.3.nonreal`

![path 3 real](https://user-images.githubusercontent.com/77984422/133965547-fc555fed-0ef7-457f-a5be-35749c5c41c4.png)
`path.3.real`

![path 4 nonreal](https://user-images.githubusercontent.com/77984422/133965582-bc800fe4-a903-4754-8d8e-93b8ff367338.png)
`path.4.nonreal`

![path 4 real](https://user-images.githubusercontent.com/77984422/133965611-012c0ee9-cd7b-4c6c-ac0a-13647b0d87b2.png)
`path.4.real`

**Comment by telk5093** [comment]
> 개인적으로는 현시 수를 신호기마다 따로 조절하는 것이 괜찮을 것 같네요.

That's too complicate
