### ISSUE TITLE
[Feature request] 경로 제한 신호기 스프라이트 추가

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanSignalSet#27]
From <https://cafe.naver.com/ottd/16424> (comment)
>혹시 경로 제한 신호기(파란색 신호기)는 따로 만드는 게 불가능한가요...?

설정의 '경로 제한 신호기를 기본 그래픽으로 보이기'를 켤 경우 경로 제한이 설정된 전자 신호기의 기둥이 파란색으로 변경되는데, 이를 한국 신호기 세트에도 적용

**Comment by EightonEight** [comment]
![block](https://user-images.githubusercontent.com/77984422/133984831-ed841a5a-5f7d-4760-b2ca-dcc80722b243.png)
`block`

![combo](https://user-images.githubusercontent.com/77984422/133984849-c38a2c75-7a73-4908-99bd-f3c0d59f8acf.png)
`combo`

![entry](https://user-images.githubusercontent.com/77984422/133984866-39c786ce-0238-4cfe-8376-f61e56a5b30e.png)
`entry`

![exit](https://user-images.githubusercontent.com/77984422/133984890-8864fa3f-14ec-47c1-9798-4115febddb3e.png)
`exit`

![noentry](https://user-images.githubusercontent.com/77984422/178227210-10b38aea-ab67-45d6-933f-da7dbea3e49f.png)
`noentry`

![oneway_path](https://user-images.githubusercontent.com/77984422/133984928-fe68963f-9d8f-4ede-89c0-d0e163a84e42.png)
`oneway_path`

![path](https://user-images.githubusercontent.com/77984422/133984952-a0e8bf8b-fe22-49f9-9b51-9bb9b5c3b6d0.png)
`path`

![programmable](https://user-images.githubusercontent.com/77984422/133984971-2b743f8f-028a-4ec2-b4ae-b1d331abb66e.png)
`programmable`

**Comment by EightonEight** [comment]
추가 신호기들
![ATC](https://user-images.githubusercontent.com/77984422/178225256-de79a24d-b935-4e55-9169-5f0f7dc5addf.png)
`ATC`

![combined color_multiple](https://user-images.githubusercontent.com/77984422/178226696-287e9489-78f8-4bef-8600-16cdfa43d6ea.png)
`combined.color_multiple`

![combined color_single](https://user-images.githubusercontent.com/77984422/178226756-5aea142f-feab-4883-a498-9da6b7124147.png)
`combined.color_single`

![combined position](https://user-images.githubusercontent.com/77984422/178226806-16c6391b-1664-4af8-82d3-7e97780b4fe9.png)
`combined.position`

![distance](https://user-images.githubusercontent.com/77984422/178226860-4b1c1e1d-e7ea-4247-a440-6aa2ee75559d.png)
`distance`

![repeating](https://user-images.githubusercontent.com/77984422/178226948-6e08b145-a47c-46eb-8f50-fd6fadd13497.png)
`repeating`

![searchlight](https://user-images.githubusercontent.com/77984422/179390654-bf9cda0a-9dac-4916-b7a8-04e5e754737d.png)
`searchlight`

![shunting](https://user-images.githubusercontent.com/77984422/178226970-57463a9d-d937-47f2-87bb-6f95117e5afd.png)
`shunting`

![TVM](https://user-images.githubusercontent.com/77984422/178226996-e5449672-989b-43ab-9a14-41418d10aa24.png)
`TVM`

**Comment by telk5093** [comment]
Recolouring으로 해결
