### ISSUE TITLE
다현시 신호기 오류

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanSignalSet#29]
터널 신호기에서 진행신호를 표출하고 있음에도 앞의 신호가 주의, 감속신호임
![화면 캡처 2021-09-22 160928](https://user-images.githubusercontent.com/88026704/134298687-941e3d32-65e8-411c-8e5e-03c001937d1c.jpg)

**Comment by JukjeonWani** [comment]
내용추가합니다. 처음 설치시에만 저런 현상이 생기고 첫 열차가 지나가면 잘 현시되는 것 같습니다.

**Comment by telk5093** [comment]
해당 현상이 재현되지 않습니다.
