### ISSUE TITLE
예상도

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanSignalSet#3]
![최종 예상도1](https://user-images.githubusercontent.com/77984422/113148560-ef122880-926c-11eb-88a2-db13090266fa.png)
1280×720
  
![최종 예상도2](https://user-images.githubusercontent.com/77984422/113148566-f0435580-926c-11eb-8438-90095ab120b0.png)
800×600
  
주: 다운로드 페이지의 대표 사진, 오프셋 기준 설정 목적으로 제작하였습니다.  
기존 신호기 스크린샷에 단순히 그림판으로 수정한 것으로, 실제 newgrf 제작 후 적용시 모습이 달라질 수 있습니다.

**Comment by telk5093** [comment]
@EightonEight 1.0.0-beta1 을 올렸습니다. 확인 바랍니다.
https://github.com/KoreanGRF/KoreanSignalSet/releases/tag/1.0.0-beta1
