### ISSUE TITLE
[Feature request] Shunting signal

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanSignalSet#30]
### 1. 색등식-다등형 입환신호기 ### 
From <https://cafe.naver.com/ottd/17033>
>혹시 기존 완목 경로신호기에 TVM신호기 처럼 매개변수로 변경이 가능한 '입환신호기(입환표지)'를 추가해주실 수 있으신지 궁금합니다.

![shunt color_multiple](https://user-images.githubusercontent.com/77984422/177723845-334106f6-42e9-4594-a4cc-f3af57189dfd.png)
`shunt.color_multiple`
- ~구식 경로 신호기에서 매개변수로 변경~( #19 와 연계)
- 역 구내, 차량기지 등에서 사용됨, (역방향)출발신호기로도 사용
- references:
  * <https://images.app.goo.gl/SgBY41oV7Drz58wT7>
  * <https://blog.naver.com/tntjrlwl/220699652903>

-----

### 2. 등열식 입환신호기 ###
![shunt position](https://user-images.githubusercontent.com/77984422/177723898-76337274-0c9b-47ad-853b-26ef40390627.png)
`shunt.position`
- 80~90년대까지 사용되었던 입환신호기
- references:
  * <http://photozou.jp/photo/show/50802/22032727>
  * <https://youtu.be/6QSuceS65AI?t=35>
  * <https://youtu.be/EnF38lcbM2c?t=205>
  * <https://youtu.be/G3lRz-9eX6Q?t=305>
  * <https://youtu.be/ksaFPEQVY7Q?t=175>
  * 철도차량운전규칙 제84조(신호현시방식) 제3호 입환신호기

**Comment by telk5093** [comment]
JGRPP 0.48.0에서 추가된 신호기 스타일 기능으로 인해 #31 을 구현하면 동시에 사용할 수 있도록 + 1과 2를 모두 적용 가능함

**Comment by EightonEight** [comment]
### 3. 색등식-단등형 입환신호기
![shunt color_single](https://user-images.githubusercontent.com/77984422/177722896-4d1bfc1a-c201-40b0-8b2c-8b91876d8524.png)
`shunt.color_single`

- references:
  * <https://blog.naver.com/izoa0486/222194759140>
  * <https://cafe.naver.com/hkct/145665>
