### ISSUE TITLE
reserve_sprites sprite allocation is too small for number of recolour sprites

### ISSUE THREAD

**Issue by JGRennison** [KoreanGRF/KoreanSignalSet#33]
In cf9c7ef, reserve_sprites(1) is called to get a sprite ID range of size 1, but this is then filled with 2 recolour sprites.
This creates problems when interoperating with other GRFs.

**Comment by telk5093** [comment]
Thanks for letting me know, I'll fix as into ``reserve_sprites(2)`` soon :)
