### ISSUE TITLE
제작자 이름 오타

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanSignalSet#4]
NewGRF 상세 정보에서 닉네임이 잘못됨
EightOnEight → EightonEight
![image](https://user-images.githubusercontent.com/77984422/113573173-8fdd5b00-9654-11eb-91f7-5458a662b6bc.png)

**Comment by telk5093** [comment]
각 이슈를 #6, #7 로 분리하고 제작자 이름 이슈만 남기겠습니다.

**Comment by EightonEight** [comment]
> 각 이슈를 #6, #7 로 분리하고 제작자 이름 이슈만 남기겠습니다.

이슈를 한꺼번에 올릴까 따로 올릴까 고민했었는데 역시 따로 올리는게 맞았네요...

**Comment by telk5093** [comment]
> 이슈를 한꺼번에 올릴까 따로 올릴까 고민했었는데 역시 따로 올리는게 맞았네요...

깃헙에서는 각 이슈를 별도로 분리해주시는 게 이슈를 추적하는 데 아무래도 도움이 될 겁니다.
많은 오픈소스 프로젝트에서도 그렇게 하고 있기도 하고요.
