### ISSUE TITLE
매개변수 변경 제안

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanSignalSet#5]
매개변수 - **파란 신호 사용**

- [x] 제목 및 설명에서 "녹색"과 어울리도록 "파란" → "파란색"으로 변경
  
- [x] 해당 매개변수를 전체가 아닌 신호기마다 개별로 적용할 수 있는지...?

매개변수 - **구식 일반 폐색 신호기를 TVM 폐색 표지로 변경**
- [x] 제목 및 설명에서 "구식 일반 폐색" → "구식 폐색"

**Comment by telk5093** [comment]
* ``파란색`` 말고 ``청색``은 어떤가요
 * 매개변수 개별 적용은 당장은 어려울 것 같네요. Python 코드를 많이 갈아엎어야할 것 같습니다. 가능은 합니다.

**Comment by telk5093** [comment]
매개변수 개별 적용만 빼고 적용되었습니다.

**Comment by telk5093** [comment]
매개변수 개별 적용도 반영되었습니다.

**Comment by EightonEight** [comment]
> * `파란색` 말고 `청색`은 어떤가요

확실히 '파란 신호' 보단 '청색 신호'라고 말하는게 나을것 같네요.
