### ISSUE TITLE
"주의 신호 사용" 매개변수 적용 시 모든 전자식 신호기 진행 시 스프라이트가 감속(YG)으로 되어있음

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanSignalSet#7]
![image](https://user-images.githubusercontent.com/10726524/113579592-7d1c5380-965f-11eb-8040-daaf41d1590d.png)

From #4 
> 모든 방향, "파란 신호 사용" 매개변수 적용 시에도 동일

**Comment by telk5093** [comment]
@EightonEight ``YB``(yellow+blue)나 ``YG``(yellow+green)가 아니라 아래와 같이 ``Y``(yellow)로만 나왔으면 한다는 말씀이신거죠?
![image](https://user-images.githubusercontent.com/10726524/113580868-4b0bf100-9661-11eb-8c1c-577664120379.png)

**Comment by EightonEight** [comment]
> @EightonEight `YB`(yellow+blue)나 `YG`(yellow+green)가 아니라 아래와 같이 `Y`(yellow)로만 나왔으면 한다는 말씀이신거죠?

아니요, 
모든 전자식 신호기 스프라이트가 `G`인 상태에서, 해당 매개변수를 적용하면 복합은 `YG`(`YB`), 출구는 `Y`로 변경되고, 나머지는 그대로 `G`를 유지하였으면 합니다.

제가 의도하고자 했던 것은 입구`G` - 복합`YG` - 출구`Y` - 정거장 - (경로`R`) 또는 입구`G` - 출구`Y` - 정거장 - (경로`R`) 가 되게 하여 자연스럽게 3현시 또는 4현시를 구현하려고 했던 것인데요. 
예상도(#3)를 참고하시면 될 것 같습니다.
![image](https://user-images.githubusercontent.com/77984422/113582070-e487d280-9662-11eb-85f9-6b716a1d7aa3.png)
