### ISSUE TITLE
전기식 프로그램 신호기(=입환 신호기) 고증 문제

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanSignalSet#8]
현직자의 조언을 받아본 결과
![image](https://user-images.githubusercontent.com/10726524/113581043-8dcdc900-9661-11eb-932b-f721b9ef263b.png)

프로그램 신호기(=입환 신호기 그래픽)는 위/아래가 동시에 진행을 현시하면 안 된다고 함 (신호기 고장으로 보고 역에 신고한다고...)

cf. 적색/적색 현시는 문제가 없음. 적색/청색 현시를 하는 경우가 있긴 함.

**Comment by EightonEight** [comment]
일단 프로그램 신호기는 현실적 그래픽 스프라이트를 제외하거나 다른 표지로 바꿔야겠네요.
입환 신호기 스프라이트를 따로 분리해서 Dutch Stations Addition Set처럼 경유지로 만들어야겠습니다...

**Comment by EightonEight** [comment]
![전자식 프로그램](https://user-images.githubusercontent.com/77984422/113957597-7ad21900-985a-11eb-90b7-26cbd94e6b2d.png)
전자식 프로그램 신호기 현실적 그래픽 스프라이트 수정 완료
- 아래 입환 신호기 현시를 정지(R, 무유도등 소등)로 고정
- 입환 신호기 스프라이트를 경유지로도 추가

**Comment by telk5093** [comment]
1.0.3에서 반영되었습니다.
